version: "3.5"
services:
  enrollments-db:
    platform: linux/amd64
    container_name: g_ms_enrollments_borrar
    build:
      context: ./.dockers/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: g_ms_enrollments_borrar
    ports:
      - "3323:3306"
    volumes:
      - ./.dockers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql